version: '3.1'
services:
  redis_db:
    image: redis
    container_name: redis_db
    ports:
      - 6379:6379
    command: redis-server --requirepass SuperSecurePass
    networks:
      - redis_net
  back:
    build:
      context: .
    container_name: back
    ports:
      - 8080:8080
    environment:
      REDIS_HOST: redis_db
      REDIS_PORT: 6379
      REDIS_PASSWORD: SuperSecurePass
    depends_on:
      - redis_db
    networks:
      - redis_net

networks:
  redis_net:
    driver: bridge
